/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_scumbag_test_jni_App */

#ifndef _Included_fr_scumbag_test_jni_App
#define _Included_fr_scumbag_test_jni_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_scumbag_test_jni_App
 * Method:    get_tcp_data
 * Signature: ()[Lfr/scumbag/test/jni/IpAndPort;
 */
JNIEXPORT jobjectArray JNICALL Java_fr_scumbag_test_jni_App_get_1tcp_1data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
